<?php
/**
 * Test class for KVDutil_AUTH_NullGebruiker.
 * Generated by PHPUnit on 2011-09-05 at 14:11:41.
 */
class KVDutil_Auth_NullGebruikerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var KVDutil_AUTH_NullGebruiker
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new KVDutil_AUTH_NullGebruiker();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object = null;
    }

    public function testIsNull() {
        $this->assertTrue( $this->object->isNull() );
    }

    public function testGetClass() {
        $this->assertEquals( 'KVDutil_Auth_Gebruiker', $this->object->getClass());
    }

    public function testGetRollenVoorApplicatie() {
        $this->assertInstanceOf( 'KVDutil_Auth_RolCollectie', $this->object->getRollenVoorApplicatie( null ));
        $this->assertEquals( 0, count($this->object->getRollenVoorApplicatie( null )));
    }

    public function testGetRollenVoorApplicatieNaam() {
        $this->assertInstanceOf( 'KVDutil_Auth_RolCollectie', $this->object->getRollenVoorApplicatieNaam( null ));
        $this->assertEquals( 0, count($this->object->getRollenVoorApplicatieNaam( null )));
    }

}

?>
