SET NAMES 'LATIN1';

-- Gebruikers-permissies
GRANT USAGE ON SCHEMA kvd_adr TO PUBLIC;

GRANT SELECT ON kvd_adr.provincie TO PUBLIC;
GRANT SELECT, UPDATE, DELETE, INSERT ON kvd_adr.provincie TO vandaeko, developer;

GRANT SELECT ON kvd_adr.gemeente TO PUBLIC;
GRANT SELECT, UPDATE, DELETE, INSERT ON kvd_adr.gemeente TO vandaeko, developer;

GRANT SELECT ON kvd_adr.deelgemeente TO PUBLIC;
GRANT SELECT, UPDATE, DELETE, INSERT ON kvd_adr.gemeente TO vandaeko, developer;
